Fix AttributeError: 'MainWindow' object has no attribute 'load_las_file'
- Changed menu connection from self.load_las_file to self.load_las_file_dialog (line 748)
- Method load_las_file does not exist; load_las_file_dialog opens file dialog and calls load_las_data